export const SIDE_BAR = {
  SIDE_BAR_LOADING: "SIDE_BAR.SIDE_BAR_LOADING",
  SIDE_BAR_SUCCESS: "SIDE_BAR.SIDE_BAR_SUCCESS",
  SIDE_BAR_FAIL: "SIDE_BAR.SIDE_BAR_FAIL",
};

export const CAT_PAGE = {
  CAT_PAGE_LOADING: "CAT_PAGE.CAT_PAGE_LOADING",
  CAT_PAGE_SUCCESS: "CAT_PAGE.CAT_PAGE_SUCCESS",
  CAT_PAGE_FAIL: "CAT_PAGE.CAT_PAGE_FAIL",
};
